name: Test
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest2

    steps:
      - name: Setup python
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
      - run: python -m pip install --upgrage pip
      - run: python install -r requirements.txt
  
      - name: Run tests
      - run: python manage.py test
