name: Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest2

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          pythonb-version: 3.9

      - name: Install dependencies
      - run: |
          python -m pip install --upgrage pip
          python install -r requirements.txt
  
      - name: Run tests
        run: |
          python manage.py test
